import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import LandingLayout from "../src/layouts/LandingLayout"
import { Button, SliderArrow, Title } from "../src/ui"
import { Swiper, SwiperSlide } from "swiper/react"
import { EffectCoverflow, Navigation, Pagination } from "swiper"
import s from "./index.module.scss"
import { Card, HeroProduct } from "../src/components"
import CreateTeacherImg from "../public/images/CreateTeacherImg.png"
import CreateStudentImg from "../public/images/CreateStudentImg.png"
import { useRef } from "react"
import cn from "classnames"

export default function Home() {
  const popularNavigationPrevRef = useRef(null)
  const popularNavigationNextRef = useRef(null)
  return (
    <>
      <Head>
        <title>Rudemy | Маркетплейс</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LandingLayout>
        <section className={s.hero}>
          <div className="container">
            <div className={s.hero__wrap}>
              <div className={s.hero__left}>
                <Title tag="h1">
                  Маркетплейс <br /> онлайн-курсов
                </Title>
                <p className={s.hero__text}>
                  Уникальная платформа для создания и продажи онлайн-курсов.
                  создайте свой курс быстро и поделитесь своими знаниями со всем
                  миром.
                </p>

                <div className={s.hero__left_btns}>
                  <Link href="/catalog">
                    <a className={s.catalog__btn}>
                      <Button>Перейти к каталогу</Button>
                    </a>
                  </Link>

                  <Link href="/registration">
                    <Button style="outlined">Присоедениться к нам</Button>
                  </Link>
                </div>
              </div>

              <div className={s.hero__right}>
                <Swiper
                  spaceBetween={0}
                  slidesPerView={"auto"}
                  effect="coverflow"
                  loop={true}
                  modules={[EffectCoverflow]}
                  pagination={{ clickable: true, dynamicBullets: true }}
                  coverflowEffect={{
                    rotate: 0,
                    stretch: 800,
                    depth: 300,
                    modifier: 1,
                    slideShadows: false,
                  }}
                >
                  <SwiperSlide>
                    <HeroProduct />
                  </SwiperSlide>
                  <SwiperSlide>
                    <HeroProduct />
                  </SwiperSlide>
                  <SwiperSlide>
                    <HeroProduct />
                  </SwiperSlide>
                  <SwiperSlide>
                    <HeroProduct />
                  </SwiperSlide>
                </Swiper>
              </div>
            </div>
          </div>
        </section>

        <section className={s.create}>
          <div className="container">
            <div className={s.create__wrap}>
              <div className={s.create__item}>
                <Title tag="h3">Создавай, обучай, зарабатывай</Title>
                <p>
                  Rudemy создана для того, что бы ты мог создавать и продвигать
                  свои авторские курсы легко и эффективно. Мы разработали
                  инновационный интерфейс который позволит тебе создавать именно
                  тот контент, который ты считаешь нужным.{" "}
                </p>
                <Link href="/login">
                  <Button className={s.create__item_btn}>Стать творцом</Button>
                </Link>
                <div className={s.create__item_img}>
                  <Image
                    src={CreateTeacherImg}
                    layout="responsive"
                    alt="Создавай, обучай, зарабатывай"
                  />
                </div>
              </div>
              <div className={s.create__item}>
                <Title tag="h3">Получай новые знания</Title>
                <p>
                  Если ты хочешь получить новые знания – ты нашел нужную
                  платформу. Зарегестрировавшись на rudemy, ты получишь доступ к
                  огромному количеству курсов и гарантированно качественному
                  контент от мастеров в своей сфере.
                </p>

                <Link href="/login">
                  <Button className={s.create__item_btn}>Стать учеником</Button>
                </Link>

                <div className={s.create__item_img}>
                  <Image
                    src={CreateStudentImg}
                    layout="responsive"
                    alt="Получай новые знания"
                  />
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className={s.how}>
          <div className="container">
            <Title tag="h2">Как это работает</Title>
            <p className={s.subtitle}>
              Посмотрите короткое видео о том, как работает наш сервис. Вы
              воочию сможете оценить все удобства и преимущства.
            </p>

            <div className={s.how__video}>
              <video loop autoPlay muted>
                <source src="./how.mp4" type="video/mp4" />
              </video>
            </div>
          </div>
        </section>

        <section className={s.popular}>
          <div className="container">
            <Title tag="h2">Популярные курсы</Title>
            <p className={s.subtitle}>
              Самые популярные курсы на rudemy сейчас. Многие создатели
              присоединились к нашей платформе и уже разместили свои курсы. Мы
              не вводим ограничений на тематику и продолжительность курсов –
              будьте свободны и смелы. Поделитесь своими знаниями с
              пользователями rudemia.
            </p>

            <div className={s.popular__top}>
              <div className={s.popular__tabs}>
                <div className={cn(s.tab, s.active)}>Все курсы</div>
                <div className={s.tab}>Java</div>
                <div className={s.tab}>HTML</div>
                <div className={s.tab}>Figma</div>
                <div className={s.tab}>C++</div>
                <div className={s.tab}>1C</div>
                <div className={s.tab}>Верстка</div>
                <div className={s.tab}>Дизайн</div>
                <div className={s.tab}>Фото</div>
                <div className={s.tab}>Видео</div>
              </div>
              <div className={s.popular__top_arrows}>
                <div ref={popularNavigationPrevRef}>
                  <SliderArrow prev />
                </div>

                <div ref={popularNavigationNextRef}>
                  <SliderArrow next />
                </div>
              </div>
            </div>
            <div className={s.popular__slider}>
              <Swiper
                slidesPerView={4}
                loop={true}
                spaceBetween={16}
                modules={[Navigation]}
                navigation={{
                  prevEl: popularNavigationPrevRef.current,
                  nextEl: popularNavigationNextRef.current,
                }}
                onBeforeInit={(swiper) => {
                  swiper.params.navigation.prevEl =
                    popularNavigationPrevRef.current
                  swiper.params.navigation.nextEl =
                    popularNavigationNextRef.current
                }}
              >
                <SwiperSlide>
                  <Card />
                </SwiperSlide>
                <SwiperSlide>
                  <Card />
                </SwiperSlide>
                <SwiperSlide>
                  <Card />
                </SwiperSlide>
                <SwiperSlide>
                  <Card />
                </SwiperSlide>
                <SwiperSlide>
                  <Card />
                </SwiperSlide>
              </Swiper>
            </div>
          </div>
        </section>

        <section className={s.how}>
          <div className="container">
            <Title>Наши преимущества</Title>
            <div className={s.how__wrap}></div>
          </div>
        </section>
      </LandingLayout>
    </>
  )
}
