import Head from "next/head"
import LandingLayout from "../src/layouts/LandingLayout"
import { Title } from "../src/ui"
import s from "./index.module.scss"
import {
  CreateSection,
  Faq,
  Hero,
  HowSection,
  PopularCourses,
} from "../src/components"

export default function Home() {
  return (
    <>
      <Head>
        <title>Rudemy | Маркетплейс</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingLayout>
        <Hero />
        <CreateSection />
        <HowSection />
        <PopularCourses />

        <section className={s.how}>
          <div className="container">
            <Title>Наши преимущества</Title>
            <div className={s.how__wrap}></div>
          </div>
        </section>
        <Faq />
      </LandingLayout>
    </>
  )
}
